# Generated by Django 2.0.6 on 2019-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=250, verbose_name="Author's names")),
                ('surnames', models.CharField(max_length=250, verbose_name="Author's surnames")),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('state', models.BooleanField(default=True, verbose_name='Author Activate/ Author Deactivate')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name of category')),
                ('state', models.BooleanField(default=True, verbose_name='Category Activate/ Category Deactivate')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
