# Generated by Django 2.0.6 on 2019-05-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.CharField(max_length=100, verbose_name='Slut')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('container', models.TextField(verbose_name='Container')),
                ('image', models.URLField(max_length=250)),
                ('state', models.BooleanField(default=True, verbose_name="Published/ Don't published")),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
